#!/bin/bash
ENGINE="snort"
IP="1.1.1.1"
PROTOCOL=""
APIKEY="1234"
RULE_PATH="/etc/nsm/rules/local.misp.rules"

for i in $ENGINE $IP $PROTOCOL $APIKEY $RULE_PATH; do
	if [ $i == "" ]; then
		echo $i is null!
		exit 0
	fi
done

wget -q --header="Authorization: $APIKEY"  $PROTOCOL://$IP/events/nids/$ENGINE/download -O $RULE_PATH

# Set correct perms
chown sguil:sguil $RULE_PATH
chmod 644 $RULE_PATH

echo ""
echo "New MISP rules downloaded!"
echo ""
