#!/bin/bash
source /etc/misp/mispcfg

for i in $ENGINE $IP $PROTOCOL $APIKEY $RULE_PATH; do
	if [ $i == "" ]; then
		echo $i is null!
		exit 0
	fi
done

wget -q --header="Authorization: $APIKEY"  $PROTOCOL://$IP/events/nids/$ENGINE/download -O $RULE_PATH

# Set correct perms
chown sguil:sguil $RULE_PATH
chmod 644 $RULE_PATH

echo ""
echo "New MISP rules downloaded!"
echo ""
