#!/bin/bash

. /usr/sbin/so-common
echo
header "Welcome to the Security Onion MISP NIDS Rules Import Wizard!"
echo

# Get responses
echo
echo "What is the ip address of your MISP instance? [x.x.x.x]"
read ip
echo

echo
echo "What protocol should be used? [http/https]"
echo
echo "For security, the protocol is set as https, by default."
echo "Would you like to continue with this protocol? [yes/no]"
read yesno
if [ $yesno  = "yes" ]; then
	:
else
	echo
	echo "Which protocol would you like to use? [http/https]"
	read protocol
fi
echo

echo
echo "Please provide an API key to access a MISP instance."
echo 
echo "You can find this information by navigating to:"
echo "https://your-misp-instance/events/automation"
read -s apikey
echo

echo
echo "Would you like to configure NIDS rules for Snort/Suricata?"
echo 
echo "Is so, please type YES below and press the ENTER key:"
echo 
read nids_rules
echo

echo
echo "Would you like to configure Intel data for Bro?"
echo 
echo "Is so, please type YES below and press the ENTER key:"
echo 
read intel
echo


echo
echo "To confirm, we will configure the following values:"
echo

echo "IP: $ip"
echo "PROTOCOL: $protocol"
echo "APIKEY: (redacted)"
echo

echo
echo "If you would like to continue, please type "YES" below:"
read confirm
echo

if [ $confirm != "YES" ]; then
        echo "Did confirm configuration...exiting..."
	echo
	exit 0
else
        #echo "Cloning GH Repo..."
	#git clone https://github.com/weslambert/securityonion-misp
	MISPCFG="/etc/misp//mispcfg"
	mkdir -p /etc/misp
        cp securityonion-misp/mispcfg $MISPCFG
	
	echo "Configuring..."
	
	# Configure download-misp with appropriate values
	sed -i "s/^IP.*/IP=\"$ip\"/" $MISPCFG
	sed -i "s/^PROTOCOL.*/PROTOCOL=\"$protocol\"/" $MISPCFG
	sed -i "s/^APIKEY.*/APIKEY=\"$apikey\"/" $MISPCFG
	sed -i "s/^INTEL=.*/INTEL=\"${intel,,}\"/" $MISPCFG
	sed -i "s/^NIDS_RULES.*/NIDS_RULES=\"${nids_rules,,}\"/" $MISPCFG
	
	# Copy misp scripts into place
	cp securityonion-misp/download-misp /usr/sbin/download-misp
	cp securityonion-misp/configure-misp /usr/sbin/configure-misp
	
	# Set perms
	chmod +x /usr/sbin/download-misp
        chmod +x /usr/sbin/configure-misp
	
	echo
	# Run configuration script 
	#/usr/sbin/configure-misp	
	echo
fi
