#!/bin/bash
#
# Copyright (C) 2018 Wes Lambert
#
# This file is part of Security Onion MISP Import Wizard.

# Security Onion MISP Import Wizard is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Security Onion MISP Import Wizard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Foobar.  If not, see <https://www.gnu.org/licenses/>.
#
# Description: Configure Security Onion to Import NIDS Rules and Zeek Intel from MISP

source /etc/misp/mispcfg

ENGINE=`grep ENGINE /etc/nsm/securityonion.conf | cut -d= -f2`

# Run download script
/usr/sbin/so-misp-download

echo ""
echo "Configuring Pulledpork..."
echo ""

PP_CONF="/etc/nsm/pulledpork/pulledpork.conf"

if [ "$ENGINE" = "snort" ]; then
	sed -i "s|^local_rules.*|local_rules=/etc/nsm/rules/local.rules,$RULE_PATH|" $PP_CONF
elif [ "$ENGINE" = "suricata" ];then
	sed -i "s|^local_rules.*|local_rules=/etc/nsm/rules/local.rules,/etc/nsm/rules/decoder-events.rules,/etc/nsm/rules/stream-events.rules,/etc/nsm/rules/http-events.rules,/etc/nsm/rules/smtp-events.rules,$RULE_PATH|" $PP_CONF
fi

if [ -f /etc/cron.d/so-misp-download ]; then
	:
else
	touch /etc/cron.d/so-misp-download
	cat << EOF > /etc/cron.d/so-misp-download
# /etc/cron.d/so-misp-download
#
# crontab entry to update MISP IDS rules

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

01 6    * * *   root    /usr/sbin/so-misp-download > /dev/null 2>&1
EOF
fi	

echo "If manually running this script, ensure that /usr/sbin/rule-update is run afterwards."

echo ""
echo "That's all folks!"
echo ""
